#!/usr/bin/env python3
"""Compare RL evaluation results against IMED results.

Usage examples:
  python RL/scripts/compare_rl_vs_imed.py \
      --rl RL/results/results_film_a.xlsx \
      --imed C:/Users/smara/chehab-unified/eval_imed_results.txt \
      --output RL/results/rl_vs_imed_comparison.csv

The script is intentionally generic:
- RL side can be an Excel file generated by the RL evaluator.
- IMED side can be an Excel/CSV file or a text log.
- If the IMED log contains numeric values, they are parsed and compared.
- If not, the script still prints the available metrics and exits cleanly.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path
from typing import Iterable

import pandas as pd


def _safe_lower(name: str) -> str:
    return str(name).strip().lower().replace(" ", "_").replace("-", "_")


def _canonicalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    rename_map = {}
    for col in list(df.columns):
        key = _safe_lower(str(col))
        canonical = {
            "budget": "Budget",
            "expression_name": "Expression Name",
            "expression": "Expression Name",
            "expr_name": "Expression Name",
            "name": "Expression Name",
            "expression_id": "Expression #",
            "expr_id": "Expression #",
            "final_noise": "Final Noise",
            "agent_final_noise": "Agent Final Noise",
            "safe_final_noise": "Safe Final Noise",
            "initial_noise": "Initial Noise",
            "agent_cost_reduction": "Agent Cost Reduction (%)",
            "safe_cost_reduction": "Safe Cost Reduction (%)",
            "cost_reduction": "Agent Cost Reduction (%)",
            "agent_violated": "Agent Violated",
            "safe_violated": "Safe Violated",
            "safety_activated": "Safety Activated",
            "rl_time_ms": "RL Time (ms)",
            "time_ms": "RL Time (ms)",
            "noise_margin": "Noise Margin",
            "initial_exec": "Initial Exec",
            "agent_final_exec": "Agent Final Exec",
            "safe_final_exec": "Safe Final Exec",
            "initial_keys": "Initial Keys",
            "agent_final_keys": "Agent Final Keys",
            "safe_final_keys": "Safe Final Keys",
        }
        if key in canonical:
            rename_map[col] = canonical[key]
    if rename_map:
        df.rename(columns=rename_map, inplace=True)
    return df


def load_rl_excel(path: str | os.PathLike[str]) -> pd.DataFrame:
    df = pd.read_excel(path)
    return _canonicalize_columns(df)


def load_imed_table(path: str | os.PathLike[str]) -> pd.DataFrame:
    path = Path(path)
    if path.suffix.lower() in {".xlsx", ".xls"}:
        return _canonicalize_columns(pd.read_excel(path))
    if path.suffix.lower() == ".csv":
        return _canonicalize_columns(pd.read_csv(path))
    if path.suffix.lower() == ".txt":
        return parse_imed_log(path)
    raise ValueError(f"Unsupported IMED file type: {path}")


def parse_imed_log(path: Path) -> pd.DataFrame:
    text = path.read_text(encoding="utf-8", errors="ignore")
    lines = text.splitlines()

    rows: list[dict] = []
    current_name = None

    for line in lines:
        bench_match = re.search(r"Benchmark '([^']+)' will be run", line)
        if bench_match:
            current_name = bench_match.group(1)
            continue

        if current_name is None:
            continue

        # Accept metric lines like: "final_ops_cost [12.5]" or "total_execution_time (s) [0.20]"
        pattern = r"(?P<metric>[A-Za-z0-9_\s]+?)\s*(?:\([^)]*\))?\s*\[(?P<value>[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)\]"
        m = re.search(pattern, line)
        if m:
            metric = m.group("metric").strip()
            value = float(m.group("value"))
            rows.append({"Expression Name": current_name, "Metric": metric, "Value": value})
            continue

        pattern2 = r"(?P<metric>[A-Za-z0-9_\s]+?)\s*[:=]\s*(?P<value>[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?)"
        m2 = re.search(pattern2, line)
        if m2:
            metric = m2.group("metric").strip()
            value = float(m2.group("value"))
            rows.append({"Expression Name": current_name, "Metric": metric, "Value": value})

    if not rows:
        return pd.DataFrame(columns=["Expression Name", "Metric", "Value"])

    df = pd.DataFrame(rows)
    return df.pivot_table(index="Expression Name", columns="Metric", values="Value", aggfunc="mean").reset_index()


def _pick_key(df: pd.DataFrame) -> tuple[str | None, str | None]:
    for col in ["Budget", "Expression Name", "Expression #"]:
        if col in df.columns:
            pass
    budget_col = next((c for c in df.columns if _safe_lower(c) == "budget"), None)
    name_col = next((c for c in df.columns if _safe_lower(c) in {"expression_name", "expression", "name"}), None)
    if name_col is None:
        name_col = next((c for c in df.columns if "name" in _safe_lower(c)), None)
    if name_col is None:
        name_col = next((c for c in df.columns if "expr" in _safe_lower(c)), None)
    return budget_col, name_col


def _compare_metrics(rl_df: pd.DataFrame, imed_df: pd.DataFrame) -> pd.DataFrame:
    rl_budget, rl_name = _pick_key(rl_df)
    imed_budget, imed_name = _pick_key(imed_df)

    if rl_name is None or imed_name is None:
        raise ValueError(
            "Could not find a benchmark identifier (Expression Name / Expression / Name) "
            "in both RL and IMED dataframes."
        )

    metric_candidates = []
    for col in rl_df.columns:
        if col in {rl_budget, rl_name}:
            continue
        if pd.api.types.is_numeric_dtype(rl_df[col]):
            metric_candidates.append(col)

    if not metric_candidates:
        raise ValueError(f"No numeric metric columns found in RL dataframe. Columns: {list(rl_df.columns)}")

    common_metrics = []
    for col in metric_candidates:
        if col in imed_df.columns and pd.api.types.is_numeric_dtype(imed_df[col]):
            common_metrics.append(col)

    if not common_metrics:
        print("No common numeric metrics found between RL and IMED results.")
        print(f"RL columns: {list(rl_df.columns)}")
        print(f"IMED columns: {list(imed_df.columns)}")
        return pd.DataFrame()

    left = rl_df[[rl_budget, rl_name] + common_metrics].copy() if rl_budget else rl_df[[rl_name] + common_metrics].copy()
    right = imed_df[[imed_budget, imed_name] + common_metrics].copy() if imed_budget else imed_df[[imed_name] + common_metrics].copy()

    merge_cols = [col for col in [rl_name, imed_name] if col is not None]
    if rl_budget and imed_budget:
        merge_cols = [rl_name, rl_budget, imed_name, imed_budget]
        left = left.rename(columns={rl_budget: "Budget", rl_name: "Expression Name"})
        right = right.rename(columns={imed_budget: "Budget", imed_name: "Expression Name"})
        merged = left.merge(right, on=["Budget", "Expression Name"], how="outer", suffixes=("_RL", "_IMED"))
    else:
        left = left.rename(columns={rl_name: "Expression Name"})
        right = right.rename(columns={imed_name: "Expression Name"})
        merged = left.merge(right, on=["Expression Name"], how="outer", suffixes=("_RL", "_IMED"))

    rows = []
    for metric in common_metrics:
        rl_col = f"{metric}_RL"
        imed_col = f"{metric}_IMED"
        if rl_col not in merged.columns or imed_col not in merged.columns:
            continue

        for _, row in merged[["Expression Name", rl_col, imed_col]].dropna(subset=[rl_col, imed_col]).iterrows():
            rows.append(
                {
                    "Expression Name": row["Expression Name"],
                    "Metric": metric,
                    "RL": row[rl_col],
                    "IMED": row[imed_col],
                    "Delta": row[rl_col] - row[imed_col],
                }
            )

    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare RL results to IMED results.")
    parser.add_argument("--rl", required=True, help="Path to RL results .xlsx/.csv file")
    parser.add_argument("--imed", required=True, help="Path to IMED results .xlsx/.csv/.txt file")
    parser.add_argument("--output", default=None, help="Optional output CSV path for the comparison table")
    args = parser.parse_args()

    rl_path = Path(args.rl)
    imed_path = Path(args.imed)

    if not rl_path.exists():
        raise FileNotFoundError(f"RL file not found: {rl_path}")
    if not imed_path.exists():
        raise FileNotFoundError(f"IMED file not found: {imed_path}")

    rl_df = load_rl_excel(rl_path)
    print(f"Loaded RL results from {rl_path} (shape={rl_df.shape})")

    try:
        imed_df = load_imed_table(imed_path)
    except Exception as exc:
        print(f"Could not parse IMED file {imed_path}: {exc}")
        imed_df = pd.DataFrame()

    print(f"Loaded IMED results from {imed_path} (shape={imed_df.shape if isinstance(imed_df, pd.DataFrame) else 'n/a'})")

    if imed_df.empty:
        print("\nNo comparable IMED data was parsed. This usually means the IMED log has no numeric values to match.")
        print(f"RL available columns: {list(rl_df.columns)}")
        return

    try:
        comparison = _compare_metrics(rl_df, imed_df)
    except Exception as exc:
        print(f"Comparison failed: {exc}")
        print(f"RL columns: {list(rl_df.columns)}")
        print(f"IMED columns: {list(imed_df.columns)}")
        return

    if comparison.empty:
        print("\nNo matching numeric metrics were found between RL and IMED files.")
        print(f"RL columns: {list(rl_df.columns)}")
        print(f"IMED columns: {list(imed_df.columns)}")
        return

    print("\nComparison summary:")
    print(comparison.head(20).to_string(index=False))

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        comparison.to_csv(out_path, index=False)
        print(f"\nSaved detailed comparison to {out_path}")


if __name__ == "__main__":
    main()
